# Generated by Django 4.2.1 on 2023-05-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_record_recorduservalue_sumofgroupperuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='groupid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sumofgroupperuser',
            name='groupid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
