# Generated by Django 4.2.1 on 2023-05-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_record_groupid_alter_sumofgroupperuser_groupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorduservalue',
            name='name',
            field=models.CharField(default='NoneNone', max_length=100),
        ),
        migrations.AddField(
            model_name='sumofgroupperuser',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
